[[plugins]]
repo = 'SirVer/ultisnips'
on_i = 1
hook_add = '''
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['eruby', 'html', 'gohtmltmpl', 'vue']
hook_add = '''
let g:use_emmet_complete_tag = 1
let g:user_emmet_settings = { 'lang' : 'ja', 'html' : { 'indentation' : '  ' }}
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']
on_map = ['<Plug>(EasyAlign)']
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
nmap <Leader>a <Plug>(EasyAlign)
'''
